name: Create CellProfiler Flatpak
jobs:
  pack-env:
    name: Pack Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: true
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.62.2
          #cache: true
          #cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          #locked: true
          #environments: prod-onlywheels
          run-install: false
          global-environments: pixi-pack
      - name: Pack Environment
        run: |
          pixi-pack --environment prod-onlywheels --platform linux-64 --use-cache .pixi_pack/cache --ignore-pypi-non-wheel --create-executable pixi.toml
          ls -Al .
      - name: Upload environment artifact
        uses: actions/upload-artifact@v6
        with:
          name: packed-environment
          path: ./environment.sh
          compression-level: 0
          overwrite: true

  create-repo:
    name: Create Flatpak Repo
    needs: pack-env
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/andyholmes/flatter/gnome:49
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: true
      - name: Download environment artifact
        uses: actions/download-artifact@v8
        with:
          name: packed-environment
          path: ./distribution/linux
      - name: Inspect downloaded artifact
        run: |
          ls -al distribution/linux
      - name: Setup GPG
        if: ${{ github.triggering_actor == github.repository_owner }}
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      #- name: Generate CNAME
      #  run: |
      #    echo "flatpak.cellprofiler.org" > CNAME
      - name: Build
        # generated artifact is named: org.cellprofiler.CellProfiler-x86_64
        uses: andyholmes/flatter@main
        with:
          files: distribution/linux/org.cellprofiler.CellProfiler.yml
          arch: x86_64
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          upload-bundles: true
          upload-pages-artifact: true
          upload-pages-includes: |
            default.css
            index.html
            # CNAME
      - name: Inspect Outputs
        run: |
          ls -al .

  # See "Github Pages" below
  deploy:
    name: Deploy Flatpak Repo
    needs: create-repo
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Delete Action Artifacts
        # artifacts attached to the action no longer necessary
        # since they have been deplyted
        id: delete-artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
            name: |
              packed-environment

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
